@baseUrl = http://localhost:3000

# RECADOS
GET {{baseUrl}}/recados
?limit=10
&offset=0
###
GET {{baseUrl}}/recados/2/
###
POST {{baseUrl}}/recados/
Content-Type: application/json

{
   "texto": "Este é um recado de teste",
    "de": "Joana",
    "para": "Maria"
}

###
PATCH  {{baseUrl}}/recados/6/
Content-Type: application/json

{
    "texto": "Recado teste",
    "lido": true
}

###
DELETE {{baseUrl}}/recados/1/

### AppControllerGetHello

# @name AppControllerGetHello

get {{baseUrl}}/home/hello

### ConceptsController

# @name ConceptsController

get {{baseUrl}}/